/// Generated by AssetsRefGenerator on 2021/04/03
class Res {
  static const String following = "assets/images/following.png";
  static const String hands = "assets/images/hands.png";
  static const String haraj = "assets/images/haraj.mp4";
  static const String icon = "assets/images/icon.png";
  static const String logo = "assets/images/logo.png";
  static const String logoWhite = "assets/images/logoWhite.png";
  static const String nodata = "assets/images/nodata.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String plus = "assets/images/plus.png";
  static const String splash = "assets/images/splash.png";
  static const String success = "assets/images/success.png";
  static const String ar = "assets/lang/ar.json";
  static const String en = "assets/lang/en.json";
}
